### ISSUE TITLE
SDK version number

### ISSUE THREAD

**Issue by agiguere** [SAP/cloud-sdk-ios#101]
As per your new version naming convention, the second digit should represent the month of the release

by example, for a June release, I would have expect

24.6.1

and not

24.4.2

Starting in 2024, the SAP BTP SDKs for iOS and Android have changed their release naming from “Major.Minor.Patch” format to “Year.Month.Patch” format. For example, a release in April 2024 is named 24.4.0. The first patch for this release will be named 24.4.1, the second will be named 24.4.2, and so on. **If the release gets delayed by a month to May, it will be named 24.5.0.**

thanks

**Comment by serajahmad01** [comment]
Hi @agiguere 

The upcoming patches for 24.4.0 will be always like 24.4.1, 24.4.2 and 24.4.x and so on. 
There will be no change in the Month even if it gets delayed for 1 month or so.

Hope this answers your question.
