### ISSUE TITLE
Xcode 16 support please

### ISSUE THREAD

**Issue by agiguere** [SAP/cloud-sdk-ios#118]
Could you please stop issuing build with Xcode 15.3 and move on with Xcode 16

The SDK 24.8.x is soo buggy with can't move on with it yet, also the IAS logging page does not work on iOS 18.1 from the simulator

<img width="1450" alt="Screenshot 2024-11-08 at 12 14 27 PM" src="https://github.com/user-attachments/assets/92f040eb-0903-4fae-a484-aeac5cb55d6e">

thanks

**Comment by MatthiasdelaRoche** [comment]
- We are building patches with the same Xcode version with which we compiled the major/minor release. Other customers insisted on this behavior and were not happy if a patch would require a higher Xcode version. This has also been requested by Apple.
- the statement “The SDK 24.8.x is soo buggy with can't move on with it yet” is not really helpful.  Please  report any bugs via customer incidents in ServiceNow.
- The IAS login page is a web page htat is not under the control by SAP BTP SDK for iOS and issues would need to be reported separately to SAP IAS.
