### ISSUE TITLE
Could not resolve package dependencies(error 401) during xmake-mobile-dev Jenkins build

### ISSUE THREAD

**Issue by LawrenceBi** [SAP/cloud-sdk-ios#17]
Hi Team,

Our app is consuming Fiori for iOS SDK. Previously we used "xmake command" to download xcframeworks from Nexus into our workspace. As Nexus is no longer available, we tried to switch it to "SPM" way as it mentioned in READ.md here. This way works perfectly in local environment, but not in Jenkins.

Here is the screenshot of the error log:
![截屏2022-09-14 18 05 17](https://user-images.githubusercontent.com/29089237/190125767-240d6ab1-a932-4e8d-a7d5-8f9c74a825b7.png)

I'm wondering if consuming SDK via SPM is the suggested way? If so, how could we overcome this no auth error from xmake Jenkins?

Please feel free to contact me via my SAP email: lawrence.bi@sap.com

Thanks & Best Regards,
Lawrence

**Comment by MarcoEidinger** [comment]
Hi, this question is related to internal usage within SAP. Hence, @serajahmad01 and I will follow up per email.
