### ISSUE TITLE
Package Collection missing Frameworks

### ISSUE THREAD

**Issue by apfund-almato** [SAP/cloud-sdk-ios#20]
The Package Collection only includes 
- FioriSwiftUI
- FioriAR
- SAPCAI
as far as I can tell.

On the last commit 'Automatically create/update collection-signed.json' failed.

**Comment by MarcoEidinger** [comment]
Thanks for the feedback. You can use [this](https://swiftpackageindex.com/SAP/collection.json) package collection url, generated by the [Swift Package Index](https://swiftpackageindex.com/), until we have as a solution from our side.

**Comment by MarcoEidinger** [comment]
Fixed with https://github.com/SAP/cloud-sdk-ios/commit/6276db51372deed1610a59fee5426a99050d1f34
