### ISSUE TITLE
How to upgrade to latest version of frameworks

### ISSUE THREAD

**Issue by JitendraPatilCG** [SAP/cloud-sdk-ios#49]
Hello Team,

We have a project which is using SAP frameworks. But frameworks versions are very old i.e. 4.0.5 . Now our plan is to upgrade our application to use latest versions of SAP frameworks. We are completely new to this, could you please help us what will be the process to upgrade very old versions to latest one and what care should be taken. 

Also is there any documentation for upgrade please? 

Is it completely paid service or can we have any trial version for testing our app.

List of SAP frameworks we are using:

1. SAPOfflineOData.framework
2. SAPOData.framework
3. SAPFoundation.framework
4. SAPFiori.framework
5. SAPCommon.framework

Regards,
Jitendra

**Comment by MarcoEidinger** [comment]
Hi,

starting with 5.0
- we distribute our framework in the .xcframework bundle format, which packs dependencies under all target platforms and architectures into a single bundle.
- provide module stability, i.e. all binary frameworks are built with module stability. This helps Xcode avoid version-locking, allowing these frameworks to be used when newer versions of Xcode or the Swift compiler are released.

Upgrading between a single release, e.g. 9.1 to 9.2, is normally as simple as replacing the xcframeworks. 

We try really hard to avoid breaking changes. In rare situations, this was not avoidable and was documented in our "What's New" documents.

I encourage you to go through the "What's New" documents to get a sense what's new/changed.

- [5.0](https://help.sap.com/docs/btp-sdk-ios/sap-btp-sdk-for-ios/whats-new?version=5.0)
- [5.1](https://help.sap.com/docs/btp-sdk-ios/sap-btp-sdk-for-ios/whats-new?version=5.1)
- [6.0](https://help.sap.com/docs/btp-sdk-ios/sap-btp-sdk-for-ios/whats-new?version=6.0)
- [6.1](https://help.sap.com/docs/btp-sdk-ios/sap-btp-sdk-for-ios/whats-new?version=6.1)
- [7.0](https://help.sap.com/docs/btp-sdk-ios/sap-btp-sdk-for-ios/whats-new?version=7.0)
- [8.0](https://help.sap.com/docs/btp-sdk-ios/sap-btp-sdk-for-ios/whats-new?version=8.0)
- [9.0](https://help.sap.com/docs/btp-sdk-ios/sap-btp-sdk-for-ios/whats-new?version=9.0)
- [9.1](https://help.sap.com/docs/btp-sdk-ios/sap-btp-sdk-for-ios/whats-new?version=9.1)
- [9.2](https://help.sap.com/docs/btp-sdk-ios/sap-btp-sdk-for-ios/whats-new?version=9.2)

You are coming from a really old release so your upgrade procedure might not be as smooth as someone upgrading from 9.1. to 9.2. Best is to attempt replacing the frameworks and fix compilation errors that pop up.

> Is it completely paid service or can we have any trial version for testing our app.

The SAP BTP SDK for iOS and SAP BTP SDK for Android are available for download on [developers.sap.com](http://developers.sap.com/) to enable developers to explore the SDKs and try out the tutorials provided on the website.

However, if you intend to use these SDKs for productive purposes, please note that a license for SAP Mobile Services is required. For more details, please see point ii under b. OTHER REQUIRED LICENSES section in the [developer license agreement](https://www.sap.com/docs/download/cmp/2020/10/master-developer-center-license-multiple-wsa.pdf).

SAP Mobile Services is a service that operates on top of SAP BTP. You can find the [pricing details on Discovery Center.](https://discovery-center.cloud.sap/protected/index.html#/serviceCatalog/mobile-services?region=all&tab=service_plan)
