### ISSUE TITLE
Not able to access https://ui.repositories.cloud.sap/www/webapp/

### ISSUE THREAD

**Issue by kgourav46** [SAP/cloud-sdk-ios#55]
<img width="1438" alt="Screenshot 2023-08-15 at 8 33 58 PM" src="https://github.com/SAP/cloud-sdk-ios/assets/7767137/e7b6fb6e-cf0f-47df-ab9b-1f408cfa2dc9">

**Comment by MarcoEidinger** [comment]
Hi @kgourav46,

do you have a valid S-user account? This is a prerequisite described [here].(https://help.sap.com/docs/RBSC/0a64be17478d4f5ba45d14ab62b0d74c/7e83dfc309834942b441fc2106c5b7f5.html)

Kind regards,
Marco

**Comment by MarcoEidinger** [comment]
@kgourav46 see [here](https://blogs.sap.com/2021/06/10/how-to-generate-a-new-s-user-id/).

Alternatively, you can download SAP BTP SDK Assistant for iOS (which includes the binary frameworks) from the [SAP Developers Trial Download site](https://developers.sap.com/trials-downloads.html?search=SAP+BTP+SDK+for+iOS) for prototyping but no productive use.

For productive use, you need a license.
