### ISSUE TITLE
Could not be resolve package dependencies

### ISSUE THREAD

**Issue by leodompr** [SAP/cloud-sdk-ios#90]
Whenever I try to add dependencies to my project, I receive this error. How to fix?

![image](https://github.com/SAP/cloud-sdk-ios/assets/94938103/69917f13-798e-492b-9ae1-5a572bae2982)

**Comment by MarcoEidinger** [comment]
Hi @leodompr, CI/CD tests indicate that using Swift Package Manager to download SAP BTP SDK for iOS 10.0.1 works with proper [configuration](https://github.com/SAP/cloud-sdk-ios?tab=readme-ov-file#configuration). **Please check the validity of your credentials.**

![Screenshot 2024-04-11 at 4 13 48 AM](https://github.com/SAP/cloud-sdk-ios/assets/4176826/3c59da2c-638a-4181-b7c4-958a86cb0bdc)

Or it might be a license issue. The download of the SAP BTP SDK for iOS binary frameworks is powered by SAP's [Repository-Based Shipment Channel](https://help.sap.com/docs/RBSC/0a64be17478d4f5ba45d14ab62b0d74c/175673b12feb41739df4f041db52fe76.html). RBSC grants access to these repositories based on a license check. License information is based on the purchased software and is attached to your S-user account. So you might want to check your current licenses as described [here](https://help.sap.com/docs/RBSC/0a64be17478d4f5ba45d14ab62b0d74c/74a9a6cd668842cc88e623ed39d8373c.html) to ensure that your user has a license for the proper product version.

**Comment by MarcoEidinger** [comment]
Hi @ravitejabb,

can you please provide me the output for the below command from your terminal:

curl -vsnO https://rbsc.repositories.cloud.sap/nexus3/repository/maven73554900100900008403/ios/SAPCommon/24.4.0/SAPCommon-24.4.0-Release.xcframework.zip

Alongside this, please check if the user has been expired or not which you can do by logging on [Technical Users' UI Home Page](https://ui.repositories.cloud.sap/www/webapp/).

Thanks,
Marco

**Comment by MarcoEidinger** [comment]
Which Xcode version are using? And do you get any failures when cloning this repository and run `swift package resolve`? The downloaded artifacts should be visible then in `.buid/artifacts/cloud-sdk-ios-main`

**Comment by MarcoEidinger** [comment]
@ravitejabb looking at a similar [example](https://github.com/apple/swift-package-manager/issues/6635) it is suggested that this might be either a caching or a keychain issue.

to clear the caches please run

```
rm -rf $HOME/Library/Caches/org.swift.swiftpm/
rm -rf $HOME/Library/org.swift.swiftpm
```

Try to resolve packages again.

For keychain issue please open Keychain Access and search for github on Passwords. Check and, if required, remove it.

Try to resolve packages again.

**Comment by MarcoEidinger** [comment]
@ravitejabb looking at a similar https://github.com/apple/swift-package-manager/issues/6635 it is suggested that this might be either a caching or a keychain issue.

to clear the caches please run

rm -rf $HOME/Library/Caches/org.swift.swiftpm/
rm -rf $HOME/Library/org.swift.swiftpm
Try to resolve packages again.

For keychain issue please open Keychain Access and search for github on Passwords. Check and, if required, remove it.

Try to resolve packages again.

**Comment by MarcoEidinger** [comment]
@leodompr please check if the following tips help you as well. If not please come back and provide more information. I'll leave this issue open for another week.

**Comment by mateuszbo** [comment]
Hi Do you have any suggestion for this log. I'm sure that login/password are correct in .netrc file. I'm using XCode 15.3.

* Couldn't find host rbsc.repositories.cloud.sap in the .netrc file; using defaults
*   Trying 52.59.87.134:443...
* Connected to rbsc.repositories.cloud.sap (52.59.87.134) port 443
* ALPN: curl offers h2,http/1.1
* (304) (OUT), TLS handshake, Client hello (1):
} [332 bytes data]
*  CAfile: /etc/ssl/cert.pem
*  CApath: none
* (304) (IN), TLS handshake, Server hello (2):
{ [91 bytes data]
* TLSv1.2 (IN), TLS handshake, Certificate (11):
{ [6937 bytes data]
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
{ [589 bytes data]
* TLSv1.2 (IN), TLS handshake, Server finished (14):
{ [4 bytes data]
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
} [70 bytes data]
* TLSv1.2 (OUT), TLS change cipher, Change cipher spec (1):
} [1 bytes data]
* TLSv1.2 (OUT), TLS handshake, Finished (20):
} [16 bytes data]
* TLSv1.2 (IN), TLS change cipher, Change cipher spec (1):
{ [1 bytes data]
* TLSv1.2 (IN), TLS handshake, Finished (20):
{ [16 bytes data]
* SSL connection using TLSv1.2 / ECDHE-RSA-AES128-GCM-SHA256
* ALPN: server did not agree on a protocol. Uses default.
* Server certificate:
*  subject: C=DE; ST=Baden-W?rttemberg; L=Walldorf; O=SAP SE; CN=rbsc.repositories.cloud.sap
*  start date: Aug 31 00:00:00 2023 GMT
*  expire date: Aug 30 23:59:59 2024 GMT
*  subjectAltName: host "rbsc.repositories.cloud.sap" matched cert's "rbsc.repositories.cloud.sap"
*  issuer: C=US; O=DigiCert Inc; CN=DigiCert TLS RSA SHA256 2020 CA1
*  SSL certificate verify ok.
* using HTTP/1.x
> GET /nexus3/repository/maven73554900100900008403/ios/SAPCommon/24.4.0/SAPCommon-24.4.0-Release.xcframework.zip HTTP/1.1
> Host: rbsc.repositories.cloud.sap
> User-Agent: curl/8.4.0
> Accept: */*
> 
< HTTP/1.1 401 Unauthorized
< Date: Wed, 24 Apr 2024 13:45:12 GMT
< Transfer-Encoding: chunked
< Connection: keep-alive
< Strict-Transport-Security: max-age=7776000
< X-Content-Type-Options: nosniff
< Content-Security-Policy: sandbox allow-forms allow-modals allow-popups allow-presentation allow-scripts allow-top-navigation
< X-XSS-Protection: 1; mode=block
< WWW-Authenticate: BASIC realm="Sonatype Nexus Repository Manager"

**Comment by MarcoEidinger** [comment]
Hi @mateuszbo, in your logs I see `Couldn't find host rbsc.repositories.cloud.sap in the .netrc file; using defaults`

Please check your `.netrc` file if it contains a such an entry:
`machine rbsc.repositories.cloud.sap login yourusername password yourpassword`

**Comment by mateuszbo** [comment]
Hi @MarcoEidinger 

I checked .netrc but it looks fine.

![Zrzut ekranu 2024-04-25 o 09 19 51](https://github.com/SAP/cloud-sdk-ios/assets/5156902/efda38e0-d8b4-4bf0-aa2e-5fe80f1f78af)

**Comment by MarcoEidinger** [comment]
Happy to hear that @mateuszbo was able to resolve the issue.

Didn't hear back from @leodompr. If the tips in this thread don't help then please open a new issue.
